### ISSUE TITLE
Сделать инструмент для ответа на отзывы менеджерами клуба

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#101]
Чтобы было выделено цветом и размещалось под выбранным отзывом.

**Comment by Ratuvog** [comment]
Нужна авторизация. Ты никак не разграничишь по иному пользователей.

**Comment by Ratuvog** [comment]
и простой ВК будет недостаточно

**Comment by Fkapishev** [comment]
Почему ВК и ФБ будет недостаточно?
Нам нужно, чтобы менеджер имел инструмент. например он пишет ответ нам на электронку, а мы его уже размещаем выделено от его имени.
Есть мысль, что не стоит давать возможность напрямую писать ответы. Некоторые манагеры клубов слегка неадекватны.

**Comment by Ratuvog** [comment]
Мне кажется это костыль. Кто будет заниматься разбором писем если их будет 100+? ИТ нужны для автоматизации. И тут вполне реально это осуществить. А модерация, это уже постфакт. Нам не нравится ответ, удаляем, а тому кто написал ответ - "извините, ваш комментарий хуёв." Снижение потребности в трудовых ресурсов на порядок.

**Comment by Ratuvog** [comment]
Пусть будет авторизация только для менеджеров

**Comment by Ratuvog** [comment]
Для поситителей через ВК и ФБ

**Comment by Fkapishev** [comment]
Ок. Согласен.
Но тут надо реализовать админку для манагеров клубов.
Этим заниматься в последнюю очередь.
Потому как до того, как попрет трафик серьезный, услугу у нас вряд ли кто-то купит.

**Comment by Ratuvog** [comment]
Админку для манагеров?Оо

**Comment by Ratuvog** [comment]
Эт скорее будет похоже личный кабинет менеджера

**Comment by Fkapishev** [comment]
Сложно?
Раз уж личный кабинет, можно ли там дать возможность редактирования информации о клубе (включая фото и т.п.)?

**Comment by Ratuvog** [comment]
Да нет, не особо сложно. Это обычный CRUD.
