### ISSUE TITLE
Реализовать индексацию картинок.

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#102]
http://help.yandex.ru/images/robot-search.xml#robot-search

**Comment by Ratuvog** [comment]
Ну а кто будет текст альтов писать?

**Comment by Fkapishev** [comment]
Давай алгоритм сделаем.
"Наименование клуба. Город. Номер картинки. Фитнес клубы на ФитПарк"

**Comment by Ratuvog** [comment]
Охх...забанят нас) "Фитнес клубы на ФитПарк". Мож хорош с этим. Все таки в меру все хорошо.

**Comment by Fkapishev** [comment]
ладно, уговорил. ) и правда перебор.
тогда "Фитнес-клуб ...Наименование клуба.... Город. Номер картинки."
