### ISSUE TITLE
До начала переезда необходимо реализовать:

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#109]
1. Выбор города.
2. Сделать админку удобнее, чтобы все в одном разделе можно было делать. Плюс загрузка сразу нескольких фото под клуб.
3. Реализовать автоматические сео-инструменты
4. Сделать админку или форму отправки инфы для клубов.
5. Сделать подбор клуба через карту Яндекса
6. Разбить список клубов города на четыре части. Места в первой части (два места) будут устанавливаться вручную в админке и выдаваться всегда на самом верху. Места во второй части (три клуба) будут между собой меняться постоянно (3,4 и 5 места соответственно). Потом часть тех клубов, у которых есть кнопки (тоже постоянно ротируются). И часть в самом низу ублюдков, у которых кнопок нет - пусть тоже только между собой ротацию устраивают. На фильтрацию эта ротация не распространяется. Там клубы выдаются уже по параметрам. Но первые пять все равно имеют приоритет перед другими. Заведу отдельный баг для этого инструмента.

**Comment by Fkapishev** [comment]
Еще хотелось бы страницу с формой заполнения для заказа программ тренировок. (макет будет ко вторнику)

**Comment by dima11221122** [comment]
Баг слишком большой, разбей на мелкие.
