### ISSUE TITLE
Отсутствует кросселинг на странице фитнес клуба

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#11]
А точнее - та херня внизу, на которой указываются "похожие" клубы.
Выборку похожих (по 5 штук) делать исходя из похожести цены на полугодовую карту.

У нас услуга будет для клубов - убрать кросселинг. За 3 500 в месяц на странице их клуба этой чудесной штуки не будет. ))

**Comment by dima11221122** [comment]
Ммм..  а насколько должны отличаться цены?

**Comment by dima11221122** [comment]
Исправлено в коммите 79a1eefb3d625d8129d951fc7650ee555bfb1e08
