### ISSUE TITLE
Сделать для комментариев дополнительный параметр

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#116]
"Положительный" и "отрицательный".
И пусть под именем писавшего будет красными буквами или, соответственно, зелеными написано.
Это сделает легче просмотр для пользователей.

насколько реально зафигачить?

**Comment by Ratuvog** [comment]
Реально-то реально, только не к спеху

**Comment by Fkapishev** [comment]
Ага.
Ок, оставляем баг на перспективу.
