### ISSUE TITLE
Склонения городов:

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#120]
А давайте в тегах выйдем из ситуации простым способом.
не будем склонять. Просто ставить отдельным словом - Казань, Набережные Челны.
Например "Фитнес-клуб Бла-бла. Казань."

А текста у нас с наименованием городов почти нет. )

**Comment by dima11221122** [comment]
а мы тем самым в плане сео не потяряем?

**Comment by Fkapishev** [comment]
Вроде не должны.
С другой стороны, что мы так мучаемся со склонениями. У нас же проблема только в титле, дескрипе и кейвордс. А их можно чуть подредактировать сразу и все.

**Comment by Fkapishev** [comment]
Нужно просто будет учитывать специфику каждого города.
например в Казане нет запросов типа "фитнес клубы Казани". Там "Фитнес Казань" просто.

**Comment by dima11221122** [comment]
я просто предлагаю все вариации тесктов, отличных для каждого города, просто в тупую сохранить. в принципе, я уже так начал делать.

**Comment by Fkapishev** [comment]
Ок. ) Я просто помню про наш разговор и буду учитывать сказанное, чтобы текста писать безотносительно города. Только раз, максимум два, указав его название.
