### ISSUE TITLE
Кнопка улучшения сайта. 

### ISSUE THREAD

**Issue by Ratuvog** [Ratuvog/fitpark.ru#125]
Должна содержать выпадающий список "высказать сове мнение о сайте" и "сообщить о клубе, которого нет на ФитПарк". ну или пункту выбора. В зависимости от выбора будут строки текста. Опишу в отдельном баге.

**Comment by dima11221122** [comment]
Исправлено в коммите 3d8225fc9559bc5617293c0278c25eb6b14bc914
