### ISSUE TITLE
Внедрить систему лайков для комментов.

### ISSUE THREAD

**Issue by Ratuvog** [Ratuvog/fitpark.ru#134]

**Comment by dima11221122** [comment]
данный баг можно закрывать?

**Comment by Fkapishev** [comment]
Если работает, то да.
Просто я ща коммент оставил на самара.фитпарк.рф и лайк поставить к нему не могу.

**Comment by dima11221122** [comment]
а ну правильно, там надо виджет для vk припилить)

**Comment by dima11221122** [comment]
Исправлено в коммите 2cdd9a260f8831244da8b53122256ec5ef5e5feb
