### ISSUE TITLE
Сделать возможность ставить "рекомендуемые клубы" к конкретной категории

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#157]
И это должны быть конкретные клубы, которые мы сможем выбрать.
Т.е. три клуба в каждой категории.
И только они будут показываться в разделе "Похожие фитнес-клубы"

**Comment by Ratuvog** [comment]
Плохое описание. Прочел трижды. Я не понял, что нужно.

**Comment by Fkapishev** [comment]
У нас есть похожие фитнес-клубы. Вот клубы, которые будут показываться в этом разделе необходимо ставить в соответствии вручную, а не случайным образом. Чуть позже опишу алгоритм

**Comment by Ratuvog** [comment]
"Вручную" и "алгоритм" не совмещаются в голове)

**Comment by Fkapishev** [comment]
До дома доберусь и напишу подробно

**Comment by Fkapishev** [comment]
Короче ситуация такова:
на данный момент в разделе "похожие фитнес клубы" выдается хрен пойми что и как.
Необходимо внедрить следующий алгоритм:
1. Три категории ценового позиционирования - эконом, средний, премиум. Они нигде юзеру не показываются, только в админках параметр должен быть.
2. Клубы, которые подключают услугу нахождения в кросс-селлинге попадают в выдачу похожих фитнес-клубов аналогичного ценового диапазона (т.е. ко всем фитнес-клубам, которые в том же ценнике).

Т.е. алгоритм есть, но клубы выбираются почти вручную. )
