### ISSUE TITLE
Сделать разделение списков вывода для разных городов

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#158]

**Comment by Fkapishev** [comment]
И от меня огромная просьба - сделать эту панель, в которой можно играться с клубами выше.
Чтобы еще на страницу вниз опускалось.
А то на этот мелком квадратике задолбаешься их перетаскивать. Особенно снизу.

**Comment by Fkapishev** [comment]
не работает изменения порядка в это списке для Тлт )

**Comment by dima11221122** [comment]
что значит разделение списков вывода?

**Comment by Fkapishev** [comment]
У нас на оба города один список вывода

**Comment by dima11221122** [comment]
неправда, у нас разные списки.зайди на тольятти.фитпарк.рф и на самара.фитпарк.рф и сравни. списки клубов разные
