### ISSUE TITLE
Ротация

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#169]
Ротация клубов в выдачах будет происходить следующим образом:

Первый блок - выделенное размещение (до 6-ти клубов). Внутренняя ротация - в случайном порядке.
Второй блок - клубы, у которых подключены кнопки обратной связи. Внутренняя ротация - чем выше вес заполненности, тем выше клуб.
Третий блок - клубы без кнопок обратной связи. Внутренняя ротация - чем выше вес, тем выше клуб.

ВЕС ЗАПОЛНЕННОСТИ КЛУБА:
Наличие не менее 2-х цен дает 30%
Наличие логотипа и не менее 8-ми фотографий дает 15%
Описание не менее 1000 знаков дает 20%
Адрес, режим работы, сайт, телефон дают 15%
Наличие не менее 5-ти отзывов дает 15%
Выбранный район города дает 5%

**Comment by Fkapishev** [comment]
Кстати, в админке надо сделать менюшку выбора клубов для первой строчки.

**Comment by dima11221122** [comment]
Федь, это новый функционал. мы его сделаем, но позже, когда весь остальной сайт будет более менее выпедорен. старайся искать баги в текущем функционале, я считаю, это более приритетно

**Comment by Fkapishev** [comment]
Базару нет, но готовьтесь. Потому как надо будет отреагировать мгновенно, если клубы изъявят желание там стационарно разместиться.
