### ISSUE TITLE
Неверная выдача клубов на главной странице

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#173]
На главной самара.фитпарк.рф выдают клубы из Тольятти.

**Comment by dima11221122** [comment]
ага, есть такое, кинь с какого по какой код фитнесклуба у нас к какому городу относятся

**Comment by dima11221122** [comment]
а все вижу в соседнем баге)

**Comment by Fkapishev** [comment]
С этим будет сложность. Я кину, но надо учитывать, что клубы будут добавляться уже в конец списка. Например в Самаре новый открывается.

Самара - до Сакура
Тольятти - до Zumba-фитнес
