### ISSUE TITLE
Ссылки для продвижения. текст один в один

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#181]
Самара:
Фитнес клубы Самары (ведет к списку клубов)
Алекс Фитнес Вива Лэнд
Алекс Фитнес Айсбрег
Планета Фитнес Уран
Планета Фитнес Арена
Ботек фитнес
Ботек Велнесс
Империал Фитнес
Кинап
Зебра
Программа тренировок (на заказ)
Жим лежа (на жим лежа на горизонтальной скамье)
Становая тяга (на нее самую)
Приседания (на приседания со штангой)
Упражнения для груди
Упражнения для ног
Упражнения для бицепсов
Упражнения для трицепсов
Упражнения для пресса
Упражнения для спины
Акции фитнес клубов
Акции ФитПарка
Скидки в фитнес клуб
Карта сайта (Ссылка на Sitemap)

Тольятти:
Фитнес клубы Тольятти (ведет к списку клубов)
Алекс Фитнес
Мир фитнеса
Фитнес Плаза
Ботек
Ева фитнес (на все клубы евы, пусть будет типа поиск по записи eva)
Мисс Фитнес
Зумба Фитнес
Альтер Эго (ссылка на Карбышева)
Альтер Эго (ссылка на Автостроителей)
Программа тренировок (на заказ)
Жим лежа (на жим лежа на горизонтальной скамье)
Становая тяга (на нее самую)
Приседания (на приседания со штангой)
Упражнения для груди
Упражнения для ног
Упражнения для бицепсов
Упражнения для трицепсов
Упражнения для пресса
Упражнения для спины
Акции фитнес клубов
Акции ФитПарка
Скидки в фитнес клуб
Карта сайта (Ссылка на Sitemap)

**Comment by Fkapishev** [comment]
Упражнений пока нет, поэтому там оставить "ссылка для продвижения".

**Comment by dima11221122** [comment]
пиши для всех городов сразу

**Comment by Fkapishev** [comment]
Казань:

Фитнес клубы Казани (ведет к списку клубов)
Планета Фитнес Казань Такташа
Планета Фитнес Казань Парина
Планета Фитнес Казань Амирхана
Планета Фитнес Казань Мусина
Алекс Фитнес Казань
Малина Фитнес (на поисковой запрос "Малина" в нашем поиске, а то их слишком дохера)
Эпицентр Казань
Икс фит Терра
X-fit Ак Барс
Программа тренировок (на заказ)
Жим лежа (на жим лежа на горизонтальной скамье)
Становая тяга (на нее самую)
Приседания (на приседания со штангой)
Упражнения для груди
Упражнения для ног
Упражнения для бицепсов
Упражнения для трицепсов
Упражнения для пресса
Упражнения для спины
Акции фитнес клубов
Акции ФитПарка
Скидки в фитнес клуб
Карта сайта (Ссылка на Sitemap)

**Comment by Fkapishev** [comment]
Челны:

Фитнес Челны (ведет к списку клубов)
Планета Фитнес Набережные Челны
Фитнес Оранж
Алекс Фитнес Челны
Броско Фитнес
Тонус Челны
Fox фитнес
Хейвус Челны
Клубы Ханака (на поиск по Ханака)
Фитнес клуб Идеал (кидай на любой из них, похеру. все равно запросов кот наплакал)
Программа тренировок (на заказ)
Жим лежа (на жим лежа на горизонтальной скамье)
Становая тяга (на нее самую)
Приседания (на приседания со штангой)
Упражнения для груди
Упражнения для ног
Упражнения для бицепсов
Упражнения для трицепсов
Упражнения для пресса
Упражнения для спины
Акции фитнес клубов
Акции ФитПарка
Скидки в фитнес клуб
Карта сайта (Ссылка на Sitemap)

**Comment by Fkapishev** [comment]
Уфа:

Фитнес клубы Уфы Челны (ведет к списку клубов)
Королев Фитнес Уфа
Менделеев Фитнес Уфа
Пушкин Фитнес Уфа
Алекс Фитнес Уфа
Фитнес Оранж Уфа
Фитнес Яблоко 
Чемпион фитнес 
Олимпия фитнес 
Фитнес Элита
Программа тренировок (на заказ)
Жим лежа (на жим лежа на горизонтальной скамье)
Становая тяга (на нее самую)
Приседания (на приседания со штангой)
Упражнения для груди
Упражнения для ног
Упражнения для бицепсов
Упражнения для трицепсов
Упражнения для пресса
Упражнения для спины
Акции фитнес клубов
Акции ФитПарка
Скидки в фитнес клуб
Карта сайта (Ссылка на Sitemap)

**Comment by Fkapishev** [comment]
Нижний Новгород

Фитнес клубы Новгород (ведет к списку клубов)
Gold`s Fitness Коминтерна
Голд Фитнес Казанское
Лайф Фитнес
Спарта фитнес (на поиск по слову Спарта)
Талия Фитнес (на поиск по слову Талия)
Рельеф фитнес на Павлова
Рельеф фитнес на Богородского
World Class Нижний Новгород (на поиск по World Class)
Физкульт (на поиск по слову Физкульт)
Программа тренировок (на заказ)
Жим лежа (на жим лежа на горизонтальной скамье)
Становая тяга (на нее самую)
Приседания (на приседания со штангой)
Упражнения для груди
Упражнения для ног
Упражнения для бицепсов
Упражнения для трицепсов
Упражнения для пресса
Упражнения для спины
Акции фитнес клубов
Акции ФитПарка
Скидки в фитнес клуб
Карта сайта (Ссылка на Sitemap)

**Comment by Fkapishev** [comment]
Жим лежа - на жим штанги лежа на горизонтальной скамье
Становая - на просто становую, она первая в упражнениях для спины
Убрать скобки, текст в скобках сугубо для того, чтобы ты понимал о чем я.
"Скидки в фитнес клубЫ", тут я прогнал. И вести сия ссылка должна на страницу акций.

**Comment by Fkapishev** [comment]
Убрать "-" перед фразой.
