### ISSUE TITLE
Алгоритм Н-тэгов не работает.

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#202]
Проверял по аналитикам, показывает не то, что должно было быть (прописывал в баге)

**Comment by dima11221122** [comment]
мм... что не так?

**Comment by dima11221122** [comment]
может конечно я что то пропустил местами

**Comment by Fkapishev** [comment]
Вот что он мне показывает:

<H1>
ФитПарк
Популярные клубы
Другие полезные разделы
Почему надо искать фитнес-клубы на ФитПарке
<H2>
все фитнес клубы Самары
ФитПоиск
Атмосфера
Оранжевое настроение
Luxury Fitness
Linia
Sport Mix
Подбор по необходимым параметрам
Фотографии фитнес клубов
Быстрая связь с менеджерами фитнес клуба
Наличие цен на абонементы
Поиск фитнес-клубов по карте
<H3>
быстрый фильтр:

**Comment by Fkapishev** [comment]
Чет как-то хреново скопировалось. В общем мне показывают, что у нас куча Н-1 тэгов. И что тэги. которые система видит вообще не те. что я писал в алгоритме.

**Comment by Fkapishev** [comment]
Мета-тэги в норме, а вот Н-заголовки нет.
