### ISSUE TITLE
Поменять нижние ссылки для продвижения

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#213]
Там таки влезает еще один блок по горизонтали.
Пусть во всех столбцах, кроме последнего, будет по пять ссылок.
А в последнем 4.

**Comment by Fkapishev** [comment]
А то пустота какая-то.

**Comment by dima11221122** [comment]
мм.. короче, чтобы не править базу, я растянул подвал по ширине

**Comment by Fkapishev** [comment]
Ок. Вижу.
