### ISSUE TITLE
В маленькой карточке клуба указывается лишь месячный вариант

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#216]
Необходимо, чтобы указывалась любая наименьшая цена, которая есть в базе. Если в базе нет месяца, то пусть три или полгода показывает.
Только если совсем цен нет, то запись должна быть "цена не указана".

**Comment by Ratuvog** [comment]
реализовать переход на фото-клуба по кнопке фотоаппрата на карточке
