### ISSUE TITLE
Имена некоторых районов содержат лишние слова

### ISSUE THREAD

**Issue by Ratuvog** [Ratuvog/fitpark.ru#223]
например, в нижнем 2 района оканчиваются на НН

**Comment by Fkapishev** [comment]
А вы сделайте так. чтобы я понимал в админке, какой район к какому городу принадлежит.
Этих ленинских и октябрьских как-то дохера. Пусть в скобках будет и видно только при выборе в админке.

**Comment by Ratuvog** [comment]
Великолепная идея!)
