### ISSUE TITLE
Ссылки в футере должны настраиваться через админку(для каждого города) 

### ISSUE THREAD

**Issue by Ratuvog** [Ratuvog/fitpark.ru#224]
Сейчас очень неудобно сделано - вся инфомрация в json. Предлагаю сделать связанную таблицу для этих целей, куда и добавлять ссылки и их имена.

Также есть предложение первый столбец использовать для размещения ссылок на общие для всех городов части.

**Comment by Fkapishev** [comment]
Поддерживаю.

**Comment by Ratuvog** [comment]
Сделал как описано. Пока хз как штатными средствами сделать так, чтобы в списке отображались клубы принадлежащие только текущему городу.

**Comment by Ratuvog** [comment]
Хотя знаю как =) сделаю)
