### ISSUE TITLE
Подобрать цвета для кнопок, иначе на некоторых мониторах кнопка выглядит вырвиглазно.. 

### ISSUE THREAD

**Issue by dima11221122** [Ratuvog/fitpark.ru#23]
Как пример - кнопка Submit new issue на гитхабе

**Comment by Fkapishev** [comment]
Если успеем.
Кнопки менять при их наличии быстро ведь?

**Comment by dima11221122** [comment]
ну да, но лучше не затягивать. если будешь подбирать, то выбирай обязательно веб-цвета

**Comment by dima11221122** [comment]
за кнопочки респект, мне прям нравится!

**Comment by dima11221122** [comment]
fb46ec8e8981a2840cfce63dbd3f3c0673773cfd
