### ISSUE TITLE
Исправление в пунктах и заголовках

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#30]
1. Убрать пока "подобрать клуб"
2. "Получить скидку" меняем на "Задать вопрос менеджеру клуба"
3. Телефон в правом верхнем углу убираем. При заходе на страницу фитнес клуба там появляется кнопка "заказать звонок от менеджера клуба"
4. Пункт "Новости" пока нахер. Только главная, фитнес - клубы и о ФитПарке.
5. Всплывающие окна должны содержать следующие поля:
           -Окно гостевого посещения - Имя, телефон, мыло, желаемую дату посещения
           -Окно задать вопрос менеджеру клуба - имя, мыло, поле вопроса
           -Окно обратного звонка - имя, телефон
           -Окно заказа абонемента - имя, фамилию, телефон, мыло, срок абонемента, примечания

**Comment by dima11221122** [comment]
1. федь, ну нихера не логично. пихать в заголовок САЙТА информацию о КЛУБЕ

**Comment by dima11221122** [comment]
b210cf17d4a68415b6debbc862dfad7ec3b54f75
