### ISSUE TITLE
Поменять иконки

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#32]
Сменить иконки адреса, телефона и сайта на наш стиль.
Выложил в Яндекс.диск.

**Comment by Fkapishev** [comment]
Для сайта - монитор.
Для адреса - домик.
Для телефона - мобилка.

**Comment by dima11221122** [comment]
Исправлено в коммите 35eb25904accc9688901a25e9660d37193c132d4
