### ISSUE TITLE
Сделать макет страницы 404

### ISSUE THREAD

**Issue by dima11221122** [Ratuvog/fitpark.ru#36]

**Comment by dima11221122** [comment]
было бы круто, если бы на странице 404 так же прослеживалась прикоьлных человечков, типа рабов-упаковщиков

**Comment by Fkapishev** [comment]
Смотрите чат

**Comment by Fkapishev** [comment]
По макету:
оставляйте всю шапку и просто добавляйте в рабочую плоскость картинку человечка со штангой.
она уже на янедкс.диске.
