### ISSUE TITLE
Мелкие недочеты

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#37]
1. В быстром фильтре вместо "дорогие" и "недорогие" сделать "по цене (сначала дороже)" и "по цене (сначала дешевле)"
2. Убрать телефон 8-800 совсем
3. Полоску в подвале перенести над текстом и под иконками соц.сетей.
4. Добавить в быстрый фильтр сортировку по рейтингу
5. Убрать "Подобрать клуб"
6. Лупа по прежнему не подает признаков жизни при наведении
7. Левая граница кнопки "главная" почему-то белая, а не черная как все остальные

**Comment by Ratuvog** [comment]
1. А зачем такая избыточность в информации (по цене (сначала дороже) - аж 4 слова);
2. Чем рейтинг от популярности отличается?
3. Кнопочки созданы с эффектом объема. Свет падает сверху-слева => слева полоски светлые, справа темные.

**Comment by Fkapishev** [comment]
1. Потому что быстрый фильтр сортирует список, а не показывает дорогие или дешевые. Люди привыкли к сортировке по цене. Есть вариант сделать просто "по цене" и рядом стрелочку вверх (когда возрастанию от дешевой к дорогой) или вниз (когда от дорогого к дешевому). Первый клик на "по цене" (лучше "по стоимости") выдает от дорогого к дешевому, а второй клик от дешевого к дорогому.
2. Популярность - гипотетически как часто заходят (или как много пользователей) на страницу фитнес клуба. В нашем случае мы сами ручками ставим популярность (что нам выгоднее и какой клуб мы любим больше)
   Рейтинг - средняя оценка клуба, поставленная юзерами.

**Comment by Fkapishev** [comment]
Относительно третьего понял, вопросов нет.

**Comment by dima11221122** [comment]
1. при наведении курсор меняется на палец

**Comment by dima11221122** [comment]
то есть это к 6 замечанию

**Comment by Ratuvog** [comment]
Кнопка все одно мертвой кажется

**Comment by Ratuvog** [comment]
Предложение разнести список на отдельные баги, этот баг закрыть. Хорошей практикой является разделять задачи. Иначе выходят накладки.

**Comment by dima11221122** [comment]
да да, федь, миша прав, не ленись делать отдельные баги, нам так легче а тебе не намного тяжелее

**Comment by Fkapishev** [comment]
Сделаю.

**Comment by Ratuvog** [comment]
Вроде все закрыто
