### ISSUE TITLE
Сортировка количества

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#38]
Предлагаю убрать ее.
Она как-то смотрится фигово.
Пусть по умолчанию 20 клубов на странице будет

**Comment by Ratuvog** [comment]
То, что фигово смотрится не обязательно убирать. Надо допилить. Я делал пагинацию, вставил что под руку попало.

**Comment by Ratuvog** [comment]
Собственно убрал палки между кол-вом страниц
