### ISSUE TITLE
Рейтинг

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#40]
Его у нас пока по прежнему не наблюдается.
Помимо звездочек под фото клуба необходимо и реализовать возможность оценки юзером при написании комментария.

**Comment by dima11221122** [comment]
ок, ток федь это последний припил к функционалу в этой версии. лучше допилить то, что есть сейчас есть.

**Comment by Fkapishev** [comment]
Не вопрос. Но рейтинг нам ооооочень нужен.

**Comment by dima11221122** [comment]
ок, понимаю

**Comment by Fkapishev** [comment]
Я вот думаю, что оценку клуба надо делать прямо кликом по звездочкам, которые под фотографией.
Просто сделать так, что при наведении они все становятся серыми и заполняются при наведении курсора на определенную звезду. А под ними мелким шрифтом написать "оцени клуб"

**Comment by Fkapishev** [comment]
Как пример - http://market.yandex.ru/model.xml?modelid=8485578&hid=6427100&int_lnk=p-goods
Справа перед комментами.

**Comment by dima11221122** [comment]
да зачем писать - таких рейтингов пруд пруди, уже всем понятно, что надо наводить

**Comment by dima11221122** [comment]
краткий тутор для дебилов писать - это не тру

**Comment by Fkapishev** [comment]
Ну а куда деваться. Надо учитывать, что дебилов будет очень много. ))
Пусть будет.
Прям в два раза меньше основного шрифта.

**Comment by dima11221122** [comment]
Не знаю, по моему это говно будет

**Comment by Ratuvog** [comment]
Если будем ориентировать продукт на дебилов, то только они одни и будут. Сомнительное занятие вкладывать силы, чтобы радовать дебилов. 
Приведу метафору о том, что в пустыне уйма субстанции называемой песком, в которой в принципе что-то всходит. А вот на одной сотке удобренной почвы взойдет много больше чем на гектаре "тупого" песка.
Эт я к тому, что давайте удобрять почву, а не рассыпать песок. Делать как будто для себя. Себя то мы дебилами не считаем?)

**Comment by Fkapishev** [comment]
Да затрахаемся мы удобрять почву. ))
Это в детстве родители должны делать.
Факт остается фактом, оценка не будет интуитивна.
Пока у меня мысли вынести пункт оценки правее отзыва или вообще вальнуть как на яндекс.маркете - на плашке перед отзывами.

**Comment by Ratuvog** [comment]
Почва в данном контексте - наш продукт. В зависимости от качества продукта на нем будут такого же качества клиенты

**Comment by dima11221122** [comment]
ну федь) нигде не пишут "нажмите сюда и будет вам счастье") можно как вариант просто алерт маленький сделать, который при наведении на рейтинг скажет тебе "выставите рейтинг" или что то типа того

**Comment by Fkapishev** [comment]
Давай тогда при наведении "оцени клуб" делать. И звездочки интерактивные, как в яндекс.маркете.

**Comment by dima11221122** [comment]
итерактивные звездочки - это тру

**Comment by Ratuvog** [comment]
Тестим!
