### ISSUE TITLE
Карточка клуба. Бесконечное добавление только что написанного комментария.

### ISSUE THREAD

**Issue by Ratuvog** [Ratuvog/fitpark.ru#49]
Как воспроизвести:
1.Переходим на карточку клуба в "Отзывы";
2.Пишем коммент;
3.Жмем "Отправить". Добавился коммент.
4. Обновляем страницу. Получаем еще одну такую же запись.
Можно обновлять пока рука не устанет.

**Comment by Fkapishev** [comment]
Забавненько ))

**Comment by dima11221122** [comment]
ага, кстати проблема такая реальная, на кф так меньше чем за минуту over 80 посылок раньше делали)))

**Comment by dima11221122** [comment]
279a229b80897c5a37b4512928fa1ccfd89f0c52
