### ISSUE TITLE
Сократить расстояние между заголовком отзыва (Оставить отзыв) и формой заполнения.

### ISSUE THREAD

**Issue by Ratuvog** [Ratuvog/fitpark.ru#50]
Пусть подсказка будет с fade-in/fade-out эффектом.

**Comment by dima11221122** [comment]
мм.. тогда сама форма будет сдвигаться, тоже нехорошо

**Comment by Ratuvog** [comment]
Тогда надо над кнопкой "Отправить" разместить это пространство. не под заголовком

**Comment by dima11221122** [comment]
я короче просто уменьшил это расстояние до 20px, иначе от выплывания диалоговому окошку плохо становится
