### ISSUE TITLE
В карточке клуба на вкладках небольшим шрифтом указывать количество отзывов, фотографий, оценок,...

### ISSUE THREAD

**Issue by Ratuvog** [Ratuvog/fitpark.ru#51]
Считаю, что это прекрасная замануха. Пример на Яндекс.Маркет. Там вкладочки в товаре.

**Comment by Fkapishev** [comment]
Всеми руками за.
И надо бы чутка уменьшить сами "вкладки", в которых написано "описание", "фото", "отзывы"
Дабы аккуратнее смотрелось. По высоте точно надо бы

**Comment by Ratuvog** [comment]
Отдельный баг)
