### ISSUE TITLE
В карточке фитнес - клуба необходимо соц.лайки

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#55]
Прямо под кнопками действий "задать вопрос", "купить карту" и т.д.
Коды предоставлю.
Важно лишь, чтобы каждая кнопка была привязана именно к этому клубу.

Будем их убеждать, чтобы они сами во всю лайкали и рассказывали друзьям. Это повысит вес нашего сайта.

**Comment by Fkapishev** [comment]
http://vk.com/developers.php?oid=-1&p=Like

**Comment by Fkapishev** [comment]
<script type="text/javascript" src="//vk.com/js/api/openapi.js?96"></script>

<script type="text/javascript">
  VK.init({apiId: 3672752, onlyWidgets: true});
</script>



<div id="vk_like"></div>

<script type="text/javascript">
VK.Widgets.Like("vk_like", {type: "mini", height: 20});
</script>

**Comment by Fkapishev** [comment]
Надо понять, как сделать счетчики для каждого клуба отдельно

**Comment by Fkapishev** [comment]
http://developers.facebook.com/docs/reference/plugins/like/

**Comment by Fkapishev** [comment]
http://aryona.ru/i_like_vkontakte
вот тут мануальчик

**Comment by dima11221122** [comment]
слушай, а есть как у футера. скриптик для нескольких соц-сетей?

**Comment by Fkapishev** [comment]
Неа.
