### ISSUE TITLE
Я тут фильтрануть попробовал...

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#57]
Сделал запрос на услуги, которых нет ни у одного клуба.
Он мне выдал пустой список (кстати, надо бы сделать надпись "с такими параметрами клубов нет")
После чего я фильтранул с бассейном (империал у нас есть с ним). И получил пустоту.
Теперь при попытке перейти на список клубов там ничего нет.

**Comment by dima11221122** [comment]
Федь, короче заполняй цены на абонементы. сделал пока возможность фильтрации цены с нуля
