### ISSUE TITLE
Необходимо переименовать все логотипы и картинки

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#58]
Как это можно сделать?

**Comment by dima11221122** [comment]
а что в их имени не нравится?)

**Comment by dima11221122** [comment]
можешь зайти по ftp и уже на серваке править

**Comment by Fkapishev** [comment]
Нам нужно использовать все возможности для seo продвижения.
Поисковики картинки тоже читают. А если у нас будут картинки с правильными наименованиями, то это даст небольшой процент роста по seo.

Где именно на ftp? Я там лазил, искал и так ничего и не понял )))

**Comment by Fkapishev** [comment]
нашел место хранения фотографий.
теперь объясните мне. как их переименовать. Жму на строчку, ввожу нужное имя, а дальше... ...а хрен знает что дальше делать. Не хочет оно режим редактирования убирать.

**Comment by dima11221122** [comment]
Там кнопочка save есть. она сохраняет
