### ISSUE TITLE
Лупа у окна поиска должна быть активной

### ISSUE THREAD

**Issue by dima11221122** [Ratuvog/fitpark.ru#6]

**Comment by dima11221122** [comment]
ммм.. так она же вроде и так активна;)

**Comment by Fkapishev** [comment]
А. Все, вижу. Тогда сделайте ее интерактивной. А то ощущение, что не работает. )) Например чуть более блеклой. А при нажатии чтобы ярче становилась.

**Comment by dima11221122** [comment]
Ок, че нить придумаем)

**Comment by dima11221122** [comment]
Исправлено в коммите 5a1a3ad47fd3bf9cf2394bcd3b3e0dc61300b1c7
