### ISSUE TITLE
Что-то у нас короткое описание в списке клубов совсем не короткое. ))

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#60]
Или это я не туда инфу записал?

**Comment by Fkapishev** [comment]
И гляньте чего с фоном описания у ботек - фитнес. Херня какая-то.

**Comment by Ratuvog** [comment]
Ммм..все описания которые ты хочешь увидеть у клуба в списке, ты пишешь в админке в таблицу Фитнес-клубы. Для описания конкретного фитнес-клуба на его страничке (полное описание) на страничке "Описания" в админке.

**Comment by Ratuvog** [comment]
А с фоном - короч, в админке там где ты пишешь описание, все форматирование текста и его фона соотв. сохранится и будет точно также отображаться на сайте.

**Comment by Ratuvog** [comment]
В описание можно вставлять даже картинки ^_^
