### ISSUE TITLE
Переход на сайт фитнес - клуба по-прежнему осуществляется без открытия новой вкладки

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#61]

**Comment by Ratuvog** [comment]
Немного непонял, надо чтобы Открывалась на новой вкладке или надо чтобы открывалась на той же?

**Comment by Fkapishev** [comment]
Нужно, чтобы при нажатии открывался сайт в новой вкладке. А страница ФитПарка оставалась.
Как в новостном блоке яндекса http://news.yandex.ru/yandsearch?cl4url=www.forbes.ru%2Fnews%2F239834-minobrnauki-uzhestochit-usloviya-sdachi-ege-po-matematike&lr=51

**Comment by Ratuvog** [comment]
Сейчас так и происходит, нет?)

**Comment by Fkapishev** [comment]
Нет. Сейчас я на этой же вкладке перехожу.

**Comment by Fkapishev** [comment]
Соответственно покидаю сайт ФитПарк.
А для нас это не гуд.

**Comment by dima11221122** [comment]
федь, я не знаю, пробовал на хроме и на мозиле. у тебя при клике на какую ссылку переходит не туда?
