### ISSUE TITLE
Если стоимость равна нулю, то тогда она не должна показываться.

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#66]

**Comment by dima11221122** [comment]
а сейчас разве не так?

**Comment by Fkapishev** [comment]
Нет. Сейчас написано 0.00

**Comment by dima11221122** [comment]
Какой клуб?

**Comment by Fkapishev** [comment]
Все. Зайди в карточку клуба. у которого нет цен - там стоят нули. А нужно, чтобы была пустота. Либо, в крайнем случаем "цена отсутствует"

**Comment by dima11221122** [comment]
а в карточке. ща посмотрим)
