### ISSUE TITLE
У меня отзывы затраиваются )))) Писал один а стало три.

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#68]
Причем я не понял, почему около каждого из них стоит разная оценка.
Оно телепатически определяет насколько я оцениваю клуб каждую микросекунду написания коммента? ))

**Comment by dima11221122** [comment]
Федь, как воспроизвел баг?

**Comment by Fkapishev** [comment]
В смысле?

**Comment by Ratuvog** [comment]
Усе поправим
