### ISSUE TITLE
У нас везде автоматом стоит "фитнес клуб"

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#69]
С возможностью добавления сегмента.
Поставьте текст "Фитнес-клуб в Самаре."
Это нам даст дополнительную индексацию.
А сегмент потом используем при категорийной фильтрации.

**Comment by dima11221122** [comment]
Ты про хлебные крошки говоришь?

**Comment by Fkapishev** [comment]
нет.
прям под адресом клуба в списке клубов. 
по сути это начальная фраза для сегмента.
