### ISSUE TITLE
Херово работает комментирование в firefox

### ISSUE THREAD

**Issue by dima11221122** [Ratuvog/fitpark.ru#71]
1. Берем фф
2. Открываем окно с комментарием.
3. пишем
4. сабмитим
5. страница сука не найдена! 
   КАК ТАК???!!!!

**Comment by Ratuvog** [comment]
В FF надо грамотно делать redirect. Его от него тошнит

**Comment by dima11221122** [comment]
Исправлено в коммите c052d004d884841d1741e7773d10b8e07e296edb
