### ISSUE TITLE
Обдумать способы перемешивания клубов при показе

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#74]
Чуть позже надо будет сделать, чтобы клубы в списке клубов показывались случайным образом. И при каждой перезагрузке страницы их место в списке менялось.
Это даст возможность играть местами и продавать верхние постоянные строчки.
Плюс будет честнее гораздо.
Лишь после фильтрации по рейтингу или популярности они будут выстраиваться четким стабильным списком.
Просто пока у себя в голове держите эту мысль на будущее.

**Comment by Ratuvog** [comment]
Думаю, что сильно на нагрузку повлияет. По сути, перемешивание - это та же сортировка.

**Comment by Fkapishev** [comment]
Хреново.
Для этого необходимо увеличить мощности хостинга?
А насколько сложно вообще реализовать данный вариант?
