### ISSUE TITLE
при переходе по ссылке с невалидным индексом, например фитпарк.рф/club/hernany в шапке сайта отображается ошибка РНР.

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#77]
Весь сайт слетает.

**Comment by dima11221122** [comment]
федь, так баг не описывают. В данном случае при переходе по ссылке с невалидным индексом, например фитпарк.рф/club/hernany в шапке сайта отображается ошибка РНР.

**Comment by dima11221122** [comment]
http://xn--80aphsgjm.xn--p1ai/club/123123123213. вот тут ваще веселуха!!!!)))
