### ISSUE TITLE
В опере у нас какой-то ужас с версткой.

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#79]
Причем лютый.

**Comment by dima11221122** [comment]
кинь скрины, я оперу поставил потыкался - да вроде все норм, единственное, что у меня не отобразилось - это рейтинг

**Comment by dima11221122** [comment]
ну и вкладочки в карточке клуба по длине несколько большеваты

**Comment by Ratuvog** [comment]
Рейтинг поправил. На будущее не использовать в js location.origin
Работает только в Хрюше и Лисе
