### ISSUE TITLE
Оценить, насколько сложно поставить кнопку ВК-лайка под каждым комментом

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#85]
Наша цель - это максимум уникального контента.
Под это дело я только что придумал акцию. которая будет связана с отзывами пользователей.
И нужна возможность оценки этих отзывов.

Насколько сложно реализовать?

**Comment by dima11221122** [comment]
по моему это велосипед. если лайки под каждым комментом, то надо контактовский виджет комментов ставить

**Comment by Fkapishev** [comment]
Не. Нам комменты контактовские не нужны.
Нужны наши родные.
Именно кнопка. Позже опишу задумку.
