### ISSUE TITLE
Замечания по новой главной странице

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#89]
Шикарно! )
1. Очепятка во фразе "Читай чужие И пиши свои"
2. "Используй фильтр..." в единственном числе слово "фильтр"
3. Заменить "...по интересным услугам" на "по интересующим услугам"
4. Использовать именно формулировку "Показать фитнес клубы"
5. В быстром фильтре текст должен быть именно черным и при наведении становиться подчеркнутым.
6. В быстром фильтре наименования услуг должны быть именно по форме "С ......" (у нас их будет 3-5 постоянных, без ротации)
7. Названия популярных клубов тоже сделать черным и подчеркнутым при наведении.
8. Кнопка перехода к списку сделать меньше по длине.
9. Шрифт надписи в кнопки перехода сделать жирным.
10. Фигурка человечка в кнопке должна быть именно справа.
11. Заголовок "удобно" убрать. Вместо него заголовком будет "Выбирайте фитнес клубы Самары легко"

**Comment by Fkapishev** [comment]
Кстати, заголовки в плане сео шикарны!
Есть все три первых H! ))

**Comment by dima11221122** [comment]
1. с жирным шрифтом в корне не согласен. федь, когда же у тебя пройдет мания на жирные подчеркнутые шрифты.. это реально утомляет

**Comment by Fkapishev** [comment]
Заливаю картинку для кнопки "перейти к фитнес клубам"
Только уменьшите кнопку по длине.
Называется "лист клубов"
