### ISSUE TITLE
Реализовать выбор города на главной и разделение клубов по городам

### ISSUE THREAD

**Issue by Fkapishev** [Ratuvog/fitpark.ru#96]
Предлагаю сделать под каждый город дополнительный урл:
www.фитпарк.рф/samara
www.фитпарк.рф/kazan
www.фитпарк.рф/toliatti
и после этого уже /clubs

**Comment by dima11221122** [comment]
в идеале конечно было бы круче например вот так самара.фитпарк.рф казань.фитпарк.рф

**Comment by Fkapishev** [comment]
Давай. Я за!
Предлагаю найти способ автоматического определения региона. А если ошиблись, то чел всегда сможет поменять город на главной. И его перекинет на поддомен.

**Comment by dima11221122** [comment]
ммм... да я тоже за) надо будет только посмотреть, как это делается

**Comment by Ratuvog** [comment]
Сумашедшие) Итак русский урл, так и еще поддоменов собрались наделать по числу городов) Это название можно впихерить, только если создавать поддомены домена фитпарк.рф

**Comment by Fkapishev** [comment]
Так мы же крейзи рашенс ))
Удобно будет. Для русскоязычных юзеров.
Хорош уже заморским алфавитом пользоваться. )

**Comment by Ratuvog** [comment]
Мне кажется для реализации это будет не эффективно в плане времени и расширяемости. Ты представляешь например мы обслуживаем 10 городов. 10 поддоменов. Хотим внести исправления в каком нибудь вместе, н-р,  добавить раздел - "Селедочные каталоги" и нам необходимо этот код писать в 10 местах! Пока не страшно? Для программиста очень страшно, n - городов, в n-раз больше необходимо контролировать кода. Мы просто будем простые вещи, которые делаются 20минут, делать сутки! Лично я за такой подход не берусь. Это абсолютно неэффективно. Насколько мне известно, других способов разместить название города в домене 3го уровня нет.

**Comment by Ratuvog** [comment]
с условием того, что мы переходим на параметризуемые урл,  то они будут выглядеть примерно так
фитпарк.рф/club/?city=Samara

**Comment by Fkapishev** [comment]
Тогда понятно. Не вариант, действительно.
А почему не сделать фитпарк.рф/самара/клубы?
Это тоже усложняет?

**Comment by Ratuvog** [comment]
Современные технологии и стандарты web пока не позволяют использовать в сегментах урл кириллицу.

**Comment by Ratuvog** [comment]
Почему невозможен вариант фитпарк.рф/samara/clubs. Насчет этого я не уверен, ибо переезд планируется на другую платформу. На данной платформе Codeigniter такое пока тоже невозможно. Самое быстрое решение, то которое я привел выше.

**Comment by Fkapishev** [comment]
Возможен. Даже вполне. ))

Ладно, если невозможно пока, то и хрен с ним. Давайте делать то, что проще и быстрее.
Главное для юзера, чтобы можно было быстро выбрать город и без проблем его просмотреть.

**Comment by Ratuvog** [comment]
Да, насчет кириллицы в url я погорячился)
